"""
Fetch a capped, deterministic subset of real riot footage from the
"Protests around the world" Kaggle dataset (jpmiller/protests-against-police-
violence) and build an id,label,filepath manifest in the same schema
scripts/select_subset.py and scripts/build_rlvs_manifest.py already produce.

Verified before writing this script (see chat / results): the dataset holds
742 real .mp4 clips (~36GB total, vertical mobile video, ~17s each) of the
Jan 6, 2021 US Capitol riot, sourced from Parler, split across four sibling
folders (`us_capitol/capitol_vids/`, `capitol_vids2/`, `capitol_vids3/`,
`capitol_vids4/` -- confirmed via the Kaggle API's paginated file listing,
not assumed from the first page). This is genuinely real riot footage -- a
much closer semantic match to the "riot" prompt class than RLVS's one-on-one
street fights.

IMPORTANT LIMITATION -- READ BEFORE INTERPRETING RESULTS:
This dataset ships NO negative-class videos and NO per-clip content labels.
The other files in the dataset (protests.csv, press_incidents.csv,
us_capitol/charges.csv, us_capitol/parler-videos-geocoded.csv) are
event-level / legal-case / geocoding records, not per-video violence
labels -- checked directly, not assumed. Every clip this script selects is
therefore labeled "riot" and this script produces NO "normal" rows. That
means scripts/evaluate.py run against this manifest alone can only report
recall on the riot class (what fraction of real riot footage CLIP correctly
calls "riot") -- not precision, not a confusion matrix with a real negative
class. Full precision/recall requires pairing this with a genuine negative
source later (deliberately not RLVS or XD-Violence yet, per current
instructions).

Unlike XD-Violence's manual-download-only host, this Kaggle dataset DOES
support scripted per-file download via the Kaggle API, so only the selected
subset is ever fetched -- never the full 36GB.
"""

import argparse
import csv
import subprocess
import sys
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from src.config import set_seed

DATASET = "jpmiller/protests-against-police-violence"
# Videos are split across multiple sibling folders (capitol_vids, capitol_vids2,
# capitol_vids3, capitol_vids4 -- 742 files total, verified via the Kaggle API's
# paginated file listing). Match any of them, not just the unsuffixed one.
VIDEO_PREFIX = "us_capitol/capitol_vids"
LABEL = "riot"

MANIFEST_DISCLAIMER = """\
# US Capitol riot-footage manifest (jpmiller/protests-against-police-violence)

Generated by `scripts/build_capitol_manifest.py`. Do not hand-edit the
sibling `.csv` -- it is kept as plain `id,label,filepath` (no comment lines)
so it loads unchanged in `scripts/evaluate.py` / `src/zero_shot_classifier.py`.

**Every row is labeled `riot`.** This dataset contains only real Jan 6 US
Capitol riot footage (sourced from Parler) -- no negative-class videos and
no per-clip content labels ship with it. The dataset's other files
(protests.csv, press_incidents.csv, charges.csv, parler-videos-geocoded.csv)
were checked directly and are event-level/legal/geocoding records, not
video-content labels.

**Consequence for evaluation:** `scripts/evaluate.py` run against this
manifest alone can only report recall on the `riot` class -- what fraction
of real riot footage CLIP correctly labels "riot" -- not precision or a
full confusion matrix. A genuine negative class (deliberately not RLVS or
XD-Violence yet) is needed before treating any accuracy/precision number
from this manifest as meaningful.
"""


def list_video_files(page_size: int = 200) -> list[str]:
    from kaggle.api.kaggle_api_extended import KaggleApi

    api = KaggleApi()
    api.authenticate()

    names = []
    token = None
    while True:
        resp = api.dataset_list_files(DATASET, page_token=token, page_size=page_size)
        for f in resp.files:
            if f.name.startswith(VIDEO_PREFIX) and f.name.lower().endswith(".mp4"):
                names.append(f.name)
        token = resp.next_page_token
        if not token:
            break
    return sorted(names)


def download_clip(remote_path: str, dest_dir: Path) -> Path:
    """Download one dataset file via the Kaggle CLI (arrives zipped) and unzip it."""
    dest_dir.mkdir(parents=True, exist_ok=True)
    filename = remote_path.split("/")[-1]
    final_path = dest_dir / filename
    if final_path.exists():
        return final_path

    subprocess.run(
        [
            "kaggle", "datasets", "download",
            "-d", DATASET,
            "-f", remote_path,
            "-p", str(dest_dir),
            "--force",
        ],
        check=True,
        capture_output=True,
        text=True,
    )

    zip_path = dest_dir / f"{filename}.zip"
    if zip_path.exists():
        with zipfile.ZipFile(zip_path) as z:
            z.extract(filename, dest_dir)
        zip_path.unlink()

    if not final_path.exists():
        raise FileNotFoundError(f"Expected {final_path} after download, not found")
    return final_path


def main():
    seed = set_seed()

    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--max-clips",
        type=int,
        default=30,
        help="Number of clips to fetch (deterministic: first N by sorted filename). "
        "Kept small by default -- these are real, uncapped-length riot clips, "
        "heavier to fetch/process than RLVS's short ones.",
    )
    parser.add_argument(
        "--out-dir",
        type=str,
        default=str(REPO_ROOT / "data" / "capitol_riot"),
        help="Local directory to download selected clips into.",
    )
    parser.add_argument(
        "--manifest",
        type=str,
        default=str(REPO_ROOT / "data" / "manifest_capitol.csv"),
        help="Output manifest path. Deliberately separate from data/manifest.csv "
        "and data/manifest_rlvs.csv.",
    )
    args = parser.parse_args()

    print(f"[build_capitol_manifest] listing video files in {DATASET} ...")
    all_files = list_video_files()
    print(f"[build_capitol_manifest] found {len(all_files)} .mp4 files total")

    selected = all_files[: args.max_clips]
    print(f"[build_capitol_manifest] selecting first {len(selected)} (seed={seed}, sorted deterministic)")

    out_dir = Path(args.out_dir)
    rows = []
    for i, remote_path in enumerate(selected, 1):
        print(f"[build_capitol_manifest] ({i}/{len(selected)}) downloading {remote_path}")
        local_path = download_clip(remote_path, out_dir)
        video_id = Path(remote_path).stem
        rows.append((video_id, LABEL, str(local_path)))

    manifest_path = Path(args.manifest)
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    with open(manifest_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["id", "label", "filepath"])
        writer.writerows(rows)

    readme_path = manifest_path.parent / f"{manifest_path.stem}.README.md"
    readme_path.write_text(MANIFEST_DISCLAIMER, encoding="utf-8")

    print(f"[build_capitol_manifest] Wrote manifest ({len(rows)} rows, all label=riot) -> {manifest_path}")
    print(f"[build_capitol_manifest] Wrote disclaimer README -> {readme_path}")
    print("[build_capitol_manifest] NOTE: no negative class in this manifest -- see README.")


if __name__ == "__main__":
    main()
