"""
Build the first genuine real-data riot-vs-normal manifest: real riot
positives (US Capitol footage, jpmiller/protests-against-police-violence)
paired with real non-riot negatives (RLVS NonViolence clips).

This supersedes the earlier RLVS-only proxy run
(data/manifest_rlvs.csv / results/rlvs_zeroshot_realdata.md), which mapped
RLVS "Violence" (one-on-one street fights) to "riot" as a stand-in while
nothing better was available. That mapping is dropped here in favor of:

    riot   <- us_capitol/capitol_vids* clips (scripts/build_capitol_manifest.py)
              real Jan 6 Capitol riot footage -- genuinely riot content.
    normal <- RLVS NonViolence clips (scripts/build_rlvs_manifest.py)
              RLVS "Violence" (fighting) is deliberately NOT included here --
              it's neither a riot nor a clean "normal" negative, so mixing it
              in would muddy a two-class riot/normal benchmark.

IMPORTANT: this only works because both source manifests already exist on
disk (run scripts/build_capitol_manifest.py and scripts/build_rlvs_manifest.py
first). This script just filters + concatenates them -- it does not download
anything itself.
"""

import argparse
import csv
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from src.config import set_seed

MANIFEST_DISCLAIMER = """\
# Combined riot/normal manifest (Capitol riot + RLVS NonViolence)

Generated by `scripts/build_protest_manifest.py`. Do not hand-edit the
sibling `.csv` -- plain `id,label,filepath`, loads unchanged in
`scripts/evaluate.py` / `src/zero_shot_classifier.py`.

**Sources:**
- `riot` rows: real US Capitol riot footage (Jan 6, 2021, via Kaggle dataset
  `jpmiller/protests-against-police-violence`), built by
  `scripts/build_capitol_manifest.py`.
- `normal` rows: RLVS `NonViolence` clips, built by
  `scripts/build_rlvs_manifest.py`.

RLVS `Violence` (one-on-one/small-group fighting) is deliberately excluded
from this manifest -- it's neither a riot nor a clean "not a riot" negative,
so including it would muddy a two-class riot/normal benchmark. See
`data/manifest_rlvs.README.md` for that earlier, now-superseded, proxy
mapping.

This is the first manifest in this project with a REAL positive class and a
REAL negative class for riot detection -- prior runs either used synthetic
dummy clips (mechanics-only) or a single-class riot-only manifest (recall
only, no precision, no confusion matrix).
"""


def main():
    set_seed()

    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--capitol-manifest",
        type=str,
        default=str(REPO_ROOT / "data" / "manifest_capitol.csv"),
    )
    parser.add_argument(
        "--rlvs-manifest",
        type=str,
        default=str(REPO_ROOT / "data" / "manifest_rlvs.csv"),
    )
    parser.add_argument(
        "--out",
        type=str,
        default=str(REPO_ROOT / "data" / "manifest_protest.csv"),
    )
    args = parser.parse_args()

    capitol_path = Path(args.capitol_manifest)
    rlvs_path = Path(args.rlvs_manifest)

    if not capitol_path.exists():
        raise SystemExit(
            f"[build_protest_manifest] Missing {capitol_path}. Run "
            "scripts/build_capitol_manifest.py first."
        )
    if not rlvs_path.exists():
        raise SystemExit(
            f"[build_protest_manifest] Missing {rlvs_path}. Run "
            "scripts/build_rlvs_manifest.py first."
        )

    rows = []
    with open(capitol_path, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row["label"] != "riot":
                continue
            rows.append((row["id"], "riot", row["filepath"]))

    with open(rlvs_path, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row["label"] != "normal":
                continue  # explicitly drop RLVS "Violence"/"riot" rows -- see docstring
            rows.append((row["id"], "normal", row["filepath"]))

    if not rows:
        raise SystemExit("[build_protest_manifest] No rows collected -- check source manifests.")

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["id", "label", "filepath"])
        writer.writerows(rows)

    readme_path = out_path.parent / f"{out_path.stem}.README.md"
    readme_path.write_text(MANIFEST_DISCLAIMER, encoding="utf-8")

    n_riot = sum(1 for _, l, _ in rows if l == "riot")
    n_normal = sum(1 for _, l, _ in rows if l == "normal")
    print(f"[build_protest_manifest] riot   : {n_riot} clips (real Capitol footage)")
    print(f"[build_protest_manifest] normal : {n_normal} clips (RLVS NonViolence)")
    print(f"[build_protest_manifest] Wrote manifest ({len(rows)} rows) -> {out_path}")
    print(f"[build_protest_manifest] Wrote disclaimer README -> {readme_path}")


if __name__ == "__main__":
    main()
