"""
Build an id,label,filepath manifest from a locally-downloaded RLVS
(Real Life Violence Situations) dataset folder, in the exact CSV schema
scripts/select_subset.py already produces -- so it drops straight into
src/zero_shot_classifier.py and scripts/evaluate.py unchanged.

Expected input layout (RLVS as distributed via Kaggle):
    <rlvs-dir>/Violence/*.mp4
    <rlvs-dir>/NonViolence/*.mp4

Label mapping -- READ BEFORE INTERPRETING RESULTS:
    Violence    -> "riot"    (see caveat below)
    NonViolence -> "normal"

RLVS is being used here as a REAL-WORLD STAND-IN for XD-Violence's Riot
class while formal access to XD-Violence is pending -- it is NOT a claim
that RLVS's "Violence" clips (predominantly one-on-one / small-group street
fights) are equivalent to riots (crowd-scale unrest). This mapping was
chosen for the sake of getting a real-data signal quickly; predictions that
land on "fighting" instead of "riot" for these clips are plausibly *more*
semantically correct than the ground-truth label being evaluated against,
not evidence that CLIP fails at riot detection. Revisit this the moment
real XD-Violence Riot clips are available.

The manifest CSV itself is kept as plain id,label,filepath with NO leading
comment lines -- evaluate.py's csv.DictReader has no comment-skipping logic,
so a "#"-prefixed header line would silently corrupt every row instead of
being ignored. The caveat above is instead written to a companion
<manifest>.README.md file next to the manifest, and must be passed through
to scripts/evaluate.py via --report-note when evaluating this manifest so it
lands in the results report too.
"""

import argparse
import csv
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from src.config import set_seed

RLVS_LABEL_MAP = {
    "Violence": "riot",
    "NonViolence": "normal",
}

MANIFEST_DISCLAIMER = """\
# RLVS -> riot/normal proxy manifest

Generated by `scripts/build_rlvs_manifest.py`. Do not hand-edit the sibling
`.csv` -- it is kept as plain `id,label,filepath` (no comment lines) so it
loads unchanged in `scripts/evaluate.py` / `src/zero_shot_classifier.py`.

**Label mapping:** `Violence` -> `riot`, `NonViolence` -> `normal`.

**Caveat:** this mapping is a REAL-WORLD STAND-IN for XD-Violence's Riot
class while formal access to XD-Violence is pending. It is NOT a claim that
RLVS "Violence" clips are equivalent to riots. RLVS "Violence" is
predominantly one-on-one / small-group physical fights -- semantically
closer to this project's existing `fighting` prompt class than to `riot`
(crowd-scale unrest). A predicted label of `fighting` on these clips is
plausibly *more* correct than the `riot` ground truth being evaluated
against, not evidence CLIP fails at riot detection. Revisit this mapping
the moment real XD-Violence Riot clips are available.
"""

VIDEO_EXTENSIONS = {".mp4", ".avi", ".mov", ".mkv"}


def collect_clips(rlvs_dir: Path, max_per_class: int | None) -> list[tuple[str, str, str]]:
    rows = []
    for folder_name, label in RLVS_LABEL_MAP.items():
        class_dir = rlvs_dir / folder_name
        if not class_dir.exists():
            print(f"[build_rlvs_manifest] WARNING: folder not found: {class_dir}")
            continue

        files = sorted(
            p for p in class_dir.iterdir() if p.is_file() and p.suffix.lower() in VIDEO_EXTENSIONS
        )
        if max_per_class is not None:
            files = files[:max_per_class]

        for path in files:
            video_id = f"{folder_name}_{path.stem}"
            rows.append((video_id, label, str(path)))

    return rows


def write_manifest(rows: list[tuple[str, str, str]], out_path: Path):
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["id", "label", "filepath"])
        writer.writerows(rows)

    readme_path = out_path.parent / f"{out_path.stem}.README.md"
    readme_path.write_text(MANIFEST_DISCLAIMER, encoding="utf-8")
    return readme_path


def main():
    set_seed()

    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--rlvs-dir",
        type=str,
        default=str(REPO_ROOT / "data" / "rlvs"),
        help="Path to the RLVS root folder containing Violence/ and NonViolence/ subfolders.",
    )
    parser.add_argument(
        "--max-per-class",
        type=int,
        default=50,
        help="Cap clips per class (RLVS has ~1000/class; kept small for a fast CPU pass). "
        "Pass 0 or a negative number for no cap.",
    )
    parser.add_argument(
        "--out",
        type=str,
        default=str(REPO_ROOT / "data" / "manifest_rlvs.csv"),
        help="Output manifest path. Deliberately NOT data/manifest.csv, so this never "
        "overwrites the XD-Violence-oriented manifest select_subset.py produces.",
    )
    args = parser.parse_args()

    rlvs_dir = Path(args.rlvs_dir)
    if not rlvs_dir.exists():
        raise SystemExit(
            f"[build_rlvs_manifest] RLVS folder not found: {rlvs_dir}\n"
            "Download it via the Kaggle API first, e.g.:\n"
            "  kaggle datasets download -d mohamedmustafa/real-life-violence-situations-dataset\n"
            f"  unzip <downloaded.zip> -d {rlvs_dir}"
        )

    max_per_class = args.max_per_class if args.max_per_class and args.max_per_class > 0 else None
    rows = collect_clips(rlvs_dir, max_per_class)

    if not rows:
        raise SystemExit(
            f"[build_rlvs_manifest] No video files found under {rlvs_dir}/Violence or "
            f"{rlvs_dir}/NonViolence. Check --rlvs-dir points at the extracted RLVS folder."
        )

    out_path = Path(args.out)
    readme_path = write_manifest(rows, out_path)

    print("[build_rlvs_manifest] Label mapping: Violence -> riot, NonViolence -> normal")
    print("[build_rlvs_manifest] NOTE: this is a real-world stand-in for XD-Violence's Riot")
    print("[build_rlvs_manifest] class, not a claim RLVS street fights equal riots. See")
    print(f"[build_rlvs_manifest] {readme_path} for the full caveat.")
    for folder_name, label in RLVS_LABEL_MAP.items():
        count = sum(1 for _, l, _ in rows if l == label)
        print(f"  {folder_name:12s} -> {label:8s}: {count} clips")
    print(f"[build_rlvs_manifest] Wrote manifest ({len(rows)} rows) -> {out_path}")
    print(f"[build_rlvs_manifest] Wrote disclaimer README -> {readme_path}")


if __name__ == "__main__":
    main()
